### ISSUE TITLE
gsoc

### ISSUE THREAD

**Issue by gauravsavanur07** [openSUSE/mentoring#103]
I am Gaurav Savanur, an undergrad student at National College of Ireland. I am primarily a full stack web developer. I have been doing some research on the OBS system I believe using React instead of ruby would be  much better option.Redux can be used to manage the state changes and Flux architecture which is used by Facebook which provides better functionality compared to to MVC model.

**Comment by Ana06** [comment]
@gauravsavanur07 do you want to rewrite OBS using React as your GSoC project? :thinking: 

Have you taken a look to OBS code base? It is a really complex project and it is for sure not possible to rewrite it using React in 3 months... and probably also not in 10 years... Moreover, there is development going in OBS everyday, which include adding new features, so the rewritten code would be outdated before it is possible to finish it. Also, that Facebook uses a framework, is not a good reason so that we also have to use it.

Please comment in the project about OBS if you have more doubts instead of open issues in this repository or contact me or other mentors directly. It would be crazy if all the students open an issue. :wink:
