### ISSUE TITLE
Shape code of double pinyin feature for ibus-libpinyin

### ISSUE THREAD

**Issue by hillwoodroc** [openSUSE/mentoring#131]
**Project Title:** Shape code of double pinyin feature for ibus-libpinyin/libpinyin

**Description:** A whole double pinyin input method is composed by pronunciation code and shape code. The libpinyin support some kinds of pronunciation codes but dosen't support shape code. The known shape code schemes, or called additional code, include Yongma. These schemes help user to reduce choice and repeated codes. We hope ibus-libpinyin would achieve the feature through adding a shape code table.

**Deliverable:** Please work on github. We will test you code. If it's stable, we can help you to merge it to upstream. 

**Mentor:**  @epico @qiangzhao @hillwoodroc

**Skills:** C, C++, python3

**Skill Level:** Medium

**Get started:** 
- IBus 1.5 API: https://github.com/ibus/ibus/wiki
- Source of libpinyin: https://github.com/libpinyin/libpinyin
- Source of ibus-libpinyin: https://github.com/libpinyin/ibus-libpinyin
- 双拼加形: https://zh.wikipedia.org/wiki/%E5%8F%8C%E6%8B%BC%E5%8A%A0%E5%BD%A2 (Just Chinese)

**Comment by snpd25** [comment]
Hey @hillwoodroc , I notice that libpinyin works on Chinese based input methods and I am not familiar with it, Will I be able to work on this project? If yes, what should I start working upon to understand the project details? Thanks.

**Comment by hillwoodroc** [comment]
Yes, you can work on this project. You don't need to learn how to use input methods. Understanding how it work is ok.
Refer: https://en.wikipedia.org/wiki/Pinyin
https://en.wikipedia.org/wiki/Input_method

**Comment by hillwoodroc** [comment]
About ZiRanMa:
E.g. The Chinese charactor “霜”. Its full ZiRanMa codes is "udjd". "ud" are pronunciation codes. "jd" are shape codes. The libpinyin has implemented the feature for pronunciation code. But there are too many Chinese characters with the same pronunciation. "jd" will give us to many choices. We want to bring the shape code feature into libpinyin, so that we will get the unique choice “霜” by the full ZiRanMa codes "udjd" without choosing.

**Comment by snpd25** [comment]
Thanks @hillwoodroc , I got the idea of input_method and pinyin. I explored the ibus-libpinyin repository, and most of the issues are in Chinese. Can you suggest any task that I may take-up for solving, so that I can understand the code structure? Thanks.

**Comment by qiangzhao** [comment]
Hi Sneha:
This topic wants to add shape code for pinyin to improve the accuracy of the recognition rate. I think to investigate the ibus-libpinyin and libpinyin's source code would help. there's no need to resolve other issues.
Thank you!

**Comment by epico** [comment]
About this proposal, I got some new ideas about user input behavior.

Instead of using ZRM shape code, I suggest to allow user to import table file like Wubi 86 or Erbi table file in setup dialog.

When user input 3-4 characters, ibus-libpinyin will query the sqlite database which contains the table file;
if only a few candidates match the user input, ibus-libpinyin will insert the matched candidates
into candidates list.

**Comment by HollowMan6** [comment]
Well, I have some questions abount the new user input behavior ideas.
> About this proposal, I got some new ideas about user input behavior.
> 
> Instead of using ZRM shape code, I suggest to allow user to import table file like Wubi 86 or Erbi table file in setup dialog.

 What do you mean by "***instead of*** using ZRM shape code", does that mean we have to give up using ZRM shape code? And according to your description,  does this sentence mean that we are going to add the function just like ibus-table?

> When user input 3-4 characters, ibus-libpinyin will query the sqlite database which contains the table file;

What about 1-2 characters? No candidates at this time? And I wonder whether the characters here means Chinese Characters or just user-inputted letters.

> if only a few candidates match the user input, ibus-libpinyin will insert the matched candidates
> into candidates list.

Since we are going to use table-based IME, how do you define "only a few candidates match the user input"? IF there are too many, we won't have candidates?

Would you please answer those questions? Thanks.

**Comment by yslking** [comment]
I have investigated the _libpinyin_ project and the _ZRM input-method_. The core feature of the ZRM, in my opinion, is the _shape code_. The ZRM input-method only supports shape codes that appear at the end of a pinyin string. i.e. pinyin strings like `xxxxxyxxx`, whose `x`s are pinyin codes and y is a shape code, are not supported; only pinyin strings like `xxxxxx`, `xxxxxy` and `xxxxxyy` are valid. The only problem is that we do not know whether a pinyin character belongs to a pinyin code or a shape code. But there are only 3 possibilities (i.e. in the form of `xxxxxx`, `xxxxxy` and `xxxxxyy`). I think the following three steps will work fine: 1) Iterate the 3 possibilities; 2) merge all candidates and guessed sentences; 3) filter candidates and guessed sentences with the shape code. I mean implement ZRM shape code and importing table files together is possible because adding ZRM shape code to libpinyin after understanding how libpinyin works is not a very tough job.  

> When user input 3-4 characters, ibus-libpinyin will query the sqlite database which contains the table file; if only a few candidates match the user input, ibus-libpinyin will insert the matched candidates
into candidates list.

I do not quite understand what you mean, either. Do you mean to add a few candidates from Wubi or other shape-based input-method to candidates list when users have only typed a short Chinese phrase (instead of a long sentence), but do not try to guess a whole sentence using these extra candidates?

**Comment by epico** [comment]
> What do you mean by "_**instead of**_ using ZRM shape code", does that mean we have to give up using ZRM shape code? And according to your description, does this sentence mean that we are going to add the function just like ibus-table?
> 

I mean we support to import some simple table file
to support Wubi 86 table or special symbols.


> What about 1-2 characters? And also what happens when there are even more than 4 characters? No candidates at this time? And I wonder whether the characters here means Chinese Characters or just user-inputted letters.
> 

I mean 3-4 user-inputted letters instead of Chinese characters.


> Since we are going to use table-based IME, how do you define "only a few candidates match the user input"? IF there are too many, we won't have candidates?
> 

We only provide table candidates in candidates list if only a few table candidates are matched.

**Comment by epico** [comment]
@yslking Iterate the 3 possibilities is slow and complicated.

I think we are considering to input some characters by shape code or table code in ibus-libpinyin.

**Comment by Inokinoki** [comment]
> About this proposal, I got some new ideas about user input behavior.
> 
> Instead of using ZRM shape code, I suggest to allow user to import table file like Wubi 86 or Erbi table file in setup dialog.
> 
> When user input 3-4 characters, ibus-libpinyin will query the sqlite database which contains the table file;
> if only a few table candidates match the user input, ibus-libpinyin will insert the matched candidates
> into candidates list.

As far as I consider, this feature could be implemented in a more flexible way: provide the possibility of customizing a concrete table and add a ZiRanMa table to implement the full feature.

Is it possible?

**Comment by epico** [comment]
> As far as I consider, this feature could be implemented in a more flexible way: provide the possibility of customizing a concrete `shape code` table and add a ZiRanMa `shape code` table to implement the full feature.
> 
> Is it possible?

Could you explain it more?

I think ibus-libpinyin will support some simple table file format,
and support to import the table provided by the user.

**Comment by Inokinoki** [comment]
> > As far as I consider, this feature could be implemented in a more flexible way: provide the possibility of customizing a concrete `shape code` table and add a ZiRanMa `shape code` table to implement the full feature.
> > Is it possible?
> 
> Could you explain it more?
> 
> I think ibus-libpinyin will support some simple table file format,
> and support to import the table provided by the user.

Yes.

In my opinion, the shape code part could be regarded as a small implementation of Wubi
(which allows users to input characters with shapes, mapped on a standard American English keyboard).
- A possibility is to treat the shape code as a mini Wubi. But this may import too much complexity in implementation;

- Another approach could start by classifying Unicode characters:
The CJK characters in the Unicode table have some segmentations,
which means most of the characters have the same part of the characters next to them.
For example, til `6B4B`, the characters which have 欠 are in one cluster. Before them, the characters with 木 part are in a continuous range:
![image](https://user-images.githubusercontent.com/8311300/76968340-095eba00-6929-11ea-9895-f42c6e188e63.png)
As a result, the shape code can be mapped in a table,
in which there are mappings between shapes(which could be reused in the other shape code)
and the corresponding ranges in the Unicode table.

- The third one can be easiest to implement, but not so intelligent and requires lots of work
Rime uses a `yaml` table, which includes mappings between each candidate and their characters.
The same way can be implemented in libpinyin. It can bring a too big table file.

Personally, I prefer to implement it through the 2nd possibility.

**Comment by Inokinoki** [comment]
The mapping mentioned in my second idea is like:

ZiRanMa shape code: Q -> shape: 七 犭 犬 丌 欠 气 且
This layer can be replaced with the other shape code encoding method.

Shape: 欠 -> Unicode range: 6B3D-6B4B
This range includes `欠次欢欣欤欥欦欧欨欩欪欫欬欭欮欯欰欱欲欳欴欵欶欷欸欹欺欻欼欽款欿歀歁歂歃歄歅歆歇歈歉歊歋`.

**Comment by epico** [comment]
Actually I prefer the Rime approach.

**Comment by epico** [comment]
I think we are changing this feature to support generic table file
instead of ZiRanMa table only.

Could you update the Project Title and Description?

**Comment by Inokinoki** [comment]
Sorry, I just keep my own idea through the classification of Unicode characters, because I don't really like the Rime approach. And it probably break cloud input for double pinyin.

**Comment by epico** [comment]
I don't think this feature will affect cloud input,
and we had better support generic table file instead of only one table
and one double pinyin scheme.

**Comment by Inokinoki** [comment]
> I don't think this feature will affect cloud input,
> and we had better support generic table file instead of only one table
> and one double pinyin scheme.

OK, I see it!

**Comment by hillwoodroc** [comment]
Close it this year.

**Comment by hillwoodroc** [comment]
Open this issue at 2021.

**Comment by qiangzhao** [comment]
will close for GSOC 2022 as offline discussion.
