### ISSUE TITLE
ibus customized pre-edit themes

### ISSUE THREAD

**Issue by qiangzhao** [openSUSE/mentoring#158]
**Project Title:** ibus pre-edit window support customized theme

**Description: The original skin function of ibus in different desktop environments is based on GNOME-shell and GTK, we need to inherit and customize it, so that users can freely choose the style they need.

**Deliverable: the modification to different desktop components to accomplish the target. 

**Mentor:** @epico @hillwoodroc @qiangzhao 

**Skills:**  C, C++, Python3

**Skill Level:** Medium

**Get started:** 

    IBus 1.5 API: https://github.com/ibus/ibus/wiki
    GTK: https://gitlab.gnome.org/GNOME/gtk/
    Gnome-shell: https://gitlab.gnome.org/GNOME/gnome-shell
    Example of Gnome-shell theme: https://www.gnome-look.org/p/1291819/

**Comment by HollowMan6** [comment]
Hi, I'm a previous year GSoC applicant from #131, and I'm interested in this project.

After searching on the Google, I noticed that currently ibus's theme is determined by the desktop theme https://github.com/rime/ibus-rime/issues/77, and we can't change it manually unless you use Gnome and change it with gnome-shell.

And another workaround to change the theme is to act in this way in Gnome: https://blog.csdn.net/weixin_30414245/article/details/96607094

So my question is, since this functionality hasn't been realized in ibus, do we just add an API for changing themes in ibus in this project? If so, currently I have no idea how to realize it, since the theme is directly determined by desktop theme. Can you give me more guidance?

**Comment by HollowMan6** [comment]
I've got some ideas from IBus Tweaker: https://extensions.gnome.org/extension/2820/ibus-tweaker/
https://github.com/tuberry/ibus-tweaker

![image](https://user-images.githubusercontent.com/43995067/111898570-da11ea00-8a61-11eb-97d6-a8b7d0e4cc8c.png)

We can make a GNOME Shell Extension that reads from the skin files (it can be rime-like color schemes https://github.com/rime-aca/color_schemes) located in the specified folder (e.g. ~/ibus_themes), users can choose a theme from the list or just follow the original GNOME theme.

**Comment by epico** [comment]
I think we will use the current gtk3 theme and gnome-shell theme for this feature.

**Comment by HollowMan6** [comment]
> I think we will use the current gtk3 theme and gnome-shell theme for this feature.

OK, I see. So combining [user-theme](https://gitlab.gnome.org/GNOME/gnome-shell-extensions/-/tree/master/extensions/user-theme) and [ibus-tweaker](https://github.com/tuberry/ibus-tweaker) will make a perfect demo. I'll try this.

**Comment by HollowMan6** [comment]
I have worked out a demo which successfully changes the IBus theme with user's current gnome-shell theme: https://github.com/HollowMan6/Customize-IBus

## e.g.

Seen as the picture below for a example. User currently choose `vim-light-doder` for gnome-shell in `User Themes`, which is a light mode theme, while IBus uses `vim-dark-doder` theme chosen by user in `Customize IBus`, which is a dark mode theme. The pre-edit window of ibus-pinyin now uses the dark theme instead of light theme.
![image](https://user-images.githubusercontent.com/43995067/112651085-03c67900-8e87-11eb-8b65-8dbbf51e146d.png)

## Realization

When user chooses a theme from the list, this extension will first read the theme CSS file, extract the IBus related style classes (`.candidate-*`), then write it to extension's `stylesheet.css`. Finally restart the GNOME-shell.

### *NOTE:*

1. Recommend to use X11. If you change theme under Wayland, all your current work may be lost.
2. Tested on Fedora 33, GNOME-shell 3.38.

## To-do
- [X] Read from user themes and apply only for ibus.
- [ ] Merge the functions in the [main branch](https://github.com/HollowMan6/Customize-IBus/tree/main) so that it can support additional functions such as customizing IBus for orientation, font and input mode auto-switch.

**Comment by HollowMan6** [comment]
Hi! I've had my proposal shared with https://drive.google.com/file/d/1a0vlrJAsqupYpBZtac9AYjAOspRQIYhw/view?usp=sharing, hope to get some feedback from the community and mentors @epico @hillwoodroc @qiangzhao

**Comment by epico** [comment]
@HollowMan6 Could you try some gnome-shell theme with customized background image?

**Comment by HollowMan6** [comment]
> @HollowMan6 Could you try some gnome-shell theme with customized background image?

hmm, I've never seen that kind of gnome-shell theme with background image for IBus candidate window before, can you provide some example?

**Comment by epico** [comment]
https://www.gnome-look.org/p/1291819/

**Comment by HollowMan6** [comment]
> URL: https://www.gnome-look.org/p/1291819/

I knew this theme earlier since it's provided in the description part.

> ```
> IBus 1.5 API: https://github.com/ibus/ibus/wiki
> GTK: https://gitlab.gnome.org/GNOME/gtk/
> Gnome-shell: https://gitlab.gnome.org/GNOME/gnome-shell
> Example of Gnome-shell theme: https://www.gnome-look.org/p/1291819/
> ```

And I've tried this theme when I started to do this idea, it was problematic when I was trying on Fedora 33, GNOME 3.38. Now this gnome-shell theme seems to still be problematic with displaying IBus candidate window correctly and with no background image showing on Fedora rawhide, GNOME 40 changed using the official [user theme](https://extensions.gnome.org/extension/19/user-themes/) extension.

![图片](https://user-images.githubusercontent.com/43995067/113661370-85fd3b80-96d8-11eb-9299-ec746bd16d76.png)

@epico Does this theme display IBus candidate window correctly on your computer, what version of GNOME-shell do you use?

**Comment by HollowMan6** [comment]
I'm able to fix this theme by adding those style code to the `gnome-shell.css`

```css
  background: url("assets/bg.png");
  background-repeat:no-repeat;
  background-size:cover;
```

![pic](https://user-images.githubusercontent.com/43995067/113663166-26a12a80-96dc-11eb-8448-aa8325acf5ab.png)

![pic](https://user-images.githubusercontent.com/43995067/113663928-76ccbc80-96dd-11eb-8535-c7828ef8ff82.png)

So I can tell that my extension can fit such kind of themes since the extension just copies the whole IBus related style blocks to the `stylesheet.css`.

If we want to add a functionality to change background image to https://github.com/HollowMan6/Customize-IBus, just write the code to modify the `.candidate-popup-content` class in my extension's `stylesheet.css` and change the background url into user wanted image url, and everything will then works fine and it's easy to realize.

**Comment by HollowMan6** [comment]
The customizing IBus background picture functionality has been added into my extension: https://github.com/HollowMan6/Customize-IBus/commit/1e00e3e77b41ba6ca896d7e06872ad49f99c2e62

**Comment by epico** [comment]
@HollowMan6 Great, thanks! :)

**Comment by hillwoodroc** [comment]
Looks great!

**Comment by epico** [comment]
@HollowMan6 Could you consider to split this extension into theme conversion tool and import ibus theme extension?

**Comment by HollowMan6** [comment]
> @HollowMan6 Could you consider to split this extension into theme conversion tool and import ibus theme extension?

Do you mean by making a script in python or shell which allow users to select from the GNOME theme CSS file, then extract the IBus related style classes (.candidate-*), finally write it to another stylesheet?

And then modify the current extension to accept the user given stylesheet? @epico

**Comment by epico** [comment]
> Do you mean by making a script in python or shell which allow users to select from the GNOME theme CSS file, then extract the IBus related style classes (.candidate-*), finally write it to another stylesheet?
> 

Right, we can use Python or JavaScript to write the conversion tool, and maintain it in a separate repo.

> And then modify the current extension to accept the user given stylesheet? @epico

Right, the import theme extension can import the modified theme file.

**Comment by HollowMan6** [comment]
I’ve created a project for changing the IBus GTK theme in a non-GNOME Shell desktop environment using Python: https://github.com/HollowMan6/IBus-Theme , later during GSoC coding period I can merge the above theme conversion tool for GNOME into it to make a complete project.

Tested on XFCE:

![image](https://user-images.githubusercontent.com/43995067/114348085-a4f84380-9b98-11eb-8e0e-9e4c02be0eba.png)

**Comment by HollowMan6** [comment]
Hi! Glad to hear that I'm accepted by GSoC 2021! I  have made a lot of progress before the results are announced and have added quite a few features for my Customize IBus extension. Here's the repos collection: https://github.com/IBus-Customize . Hope to get some feedback. Issues are welcome! 

And here's a guideline for using Customize IBus (in Chinese) : https://blog.csdn.net/qq_18572023/article/details/116331601

**Comment by epico** [comment]
Look forward to work on this feature with you during GSoC! :slightly_smiling_face:

**Comment by AKACHI-4** [comment]
Hello people's i am a new comer can u explain me little bit more bcz now it is bit tough to me to understand it ....

.

**Comment by HollowMan6** [comment]
@AKACHI-4 I guess you have to find another one as this is an idea for [GSoC 2021](https://summerofcode.withgoogle.com/archive/2021/projects/6295506795364352/), not for this year.

**Comment by AKACHI-4** [comment]
@HollowMan6 okay thanku

**Comment by qiangzhao** [comment]
close for GSOC 2022 as offline discussion.
