### ISSUE TITLE
Porting PRoot to Rust

### ISSUE THREAD

**Issue by oxr463** [openSUSE/mentoring#162]
**Project Title:** Porting PRoot to Rust

**Description:**

There is already a proof of concept in progress, (See: https://github.com/proot-me/proot-rs). However, this implementation is very basic and only runs on a single architecture. Work is still needed to complete a functioning prototype, as outlined here, <https://github.com/proot-me/proot-rs/issues/1>:

> Remaining steps for the bare minimum (single-tracee, no glue, no extensions, no ptrace-translation, no unix-socket translation, no qemu, -r/-R, -w and -b cli options only, no seccomp, and x86-64 with 64bits programs only)

**Deliverable:**

Fully functional, albeit minimal, PRoot implementation written in Rust.

**Mentor:** @oxr463

**Skills:** ptrace, rust

**Skill Level:** Medium

**Get started:** See: https://github.com/proot-me/proot-rs/issues/1

**Comment by KB5201314** [comment]
@oxr463 

Hi oxr463,

I'm imlk, and I am studying computer science at Beijing University of Posts and Telecommunications in China. I have experience in developing toy operating systems using Rust, and I used to work as an intern in a company that uses the Rust language. 

I saw this idea on GSOC. I am very interested in the work of Porting PRoot to Rust and intend to participate in it. 

I forked the code (https://github.com/KB5201314/proot-rs) and have made some changes:

- CI: I noticed that the introduction of Travis CI happened before the GitHub Action was released, so I replaced it with the Github Action, which is more convenient.  
  https://github.com/KB5201314/proot-rs/blob/imlk-dev/.github/workflows/rust.yml
  https://github.com/KB5201314/proot-rs/actions

- Fix build problems, such as build failure caused by `lazy_static`, `llvm_asm`, and `syscall`

- Pre-commit hook: Setup git hooks so that we can check the code format before submitting
  https://github.com/KB5201314/proot-rs/commit/da19bd12ea667f530dced82e24cca782571ee81e
- Fixed some problems detected by `cargo clippy`
  https://github.com/KB5201314/proot-rs/commit/7d537c0ed0874f11d6e7d67f0668c7ab0907414c

Currently, I'm still gaining an understanding of the existing code. I think it will be beneficial to start with fixing the `cargo test` failure. :)

**Comment by oxr463** [comment]
@KB5201314 sounds awesome! Please join our Gitter so we can chat in real time, (https://gitter.im/proot-me/devs).

Also, it would be cool to get a PR going for these changes.

**Comment by KB5201314** [comment]
> @KB5201314 sounds awesome! Please join our Gitter so we can chat in real time, (https://gitter.im/proot-me/devs).
> 
> Also, it would be cool to get a PR going for these changes.

Thank you, I have created a PR https://github.com/proot-me/proot-rs/pull/12

**Comment by oxr463** [comment]
This is done per, https://github.com/proot-me/proot-rs/releases/tag/v0.1.0
